logging:
  level:
    root: INFO
    com.example.poc: DEBUG

---
# Test profile
spring:
  config:
    activate:
      on-profile: test
  
  main:
    banner-mode: "off"
    
logging:
  level:
    root: INFO
    com.example.poc: DEBUG
